# Artificial Neural Network

# Dataset

### Layout

* Columns: 5
	* Engine temperature
	* Exhaust vacuum
	* Ambient pressure
	* Relative humidity
	* Energy output
* Rows: 1000s of observations
	* Each row represents observation of captured metrics at a power plant
		* Features:
			* Engine temperature
			* Exhaust vacuum
			* Ambient pressure
			* Relative humidity
		* Dependent variable:
			* Energy output

### Background

* Real world dataset from UCI ML repository
	* Website that contains many real-world datasets in which to practice ML
* Combined cycle power plant dataset
* A combined-cycle power plant (CCCP) is an electrical power plant in which a Gas Turbine (GT) and a Steam Turbine (ST) are used in combination to produce more electrical energy from the same fuel than would be possible from a single cycle power plant
* The gas turbine compresses air and mixes it with a fuel heated to a very high temperature
* The hot air-fuel mixture moves through the blades, making them spin
* The fast-spinning gas turbine drives a generator to generate electricity
* The exhaust (waste) heat escaped through the exhaust stack of the gas turbine is used by a Heat Recovery Steam Generator (HSRG) system to produce steam that spins a steam turbine
* This steam turbine drives a generator to produce additional electricity
* CCCP is assumed to produce 50% more energy than a single power plant

### Goals

* Build a regression model from an ANN using stochastic gradient descent to predict the energy output

---

## Import Libraries

In [75]:
import numpy as np
import openpyxl
import pandas as pd
import tensorflow as tf

In [76]:
tf.__version__

'2.19.0'

---

## Part 1 - Data Preprocessing

### Import Dataset

In [77]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [78]:
print(*X[:25], sep='\n')

[  14.96   41.76 1024.07   73.17]
[  25.18   62.96 1020.04   59.08]
[   5.11   39.4  1012.16   92.14]
[  20.86   57.32 1010.24   76.64]
[  10.82   37.5  1009.23   96.62]
[  26.27   59.44 1012.23   58.77]
[  15.89   43.96 1014.02   75.24]
[   9.48   44.71 1019.12   66.43]
[  14.64   45.   1021.78   41.25]
[  11.74   43.56 1015.14   70.72]
[  17.99   43.72 1008.64   75.04]
[  20.14   46.93 1014.66   64.22]
[  24.34   73.5  1011.31   84.15]
[  25.71   58.59 1012.77   61.83]
[  26.19   69.34 1009.48   87.59]
[  21.42   43.79 1015.76   43.08]
[  18.21   45.   1022.86   48.84]
[  11.04   41.74 1022.6    77.51]
[  14.45   52.75 1023.97   63.59]
[  13.97   38.47 1015.15   55.28]
[  17.76   42.42 1009.09   66.26]
[   5.41   40.07 1019.16   64.77]
[   7.76   42.28 1008.52   83.31]
[  27.23   63.9  1014.3    47.19]
[  27.36   48.6  1003.18   54.93]


In [79]:
print(*y[:25], sep='\n')

463.26
444.37
488.56
446.48
473.9
443.67
467.35
478.42
475.98
477.5
453.02
453.99
440.29
451.28
433.99
462.19
467.54
477.2
459.85
464.3
468.27
495.24
483.8
443.61
436.06


### Split Dataset into Training Set and Test Set

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

---

## Part 2 - Build ANN

### Initialize ANN

In [81]:
ann = tf.keras.models.Sequential()

### Add Input layer and First Hidden Layer

In [82]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Add Second Hidden Layer

In [83]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Add Output Layer

In [84]:
ann.add(tf.keras.layers.Dense(units=1))

---

## Part 3 - Train ANN

### Compile ANN

In [85]:
ann.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

### Train ANN on Training Set

In [86]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 614us/step - accuracy: 0.0000e+00 - loss: 128053.4609
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.0000e+00 - loss: 409.7357
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - accuracy: 0.0000e+00 - loss: 393.3746
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step - accuracy: 0.0000e+00 - loss: 381.5034
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.0000e+00 - loss: 360.4089
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.0000e+00 - loss: 348.2657
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.0000e+00 - loss: 318.2599
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.0000e+00 - loss: 292.4984
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - accuracy: 0.0000e+00 - loss: 277.0300
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.0000e+00 - loss: 252.6193
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 4

---

## Make Predictions and Evaluate Model

### Predict Test Set Results

In [87]:
y_pred = ann.predict(X_test)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 594us/step


In [92]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[429.2  431.23]
 [460.2  460.01]
 [463.71 461.14]
 ...
 [470.89 473.26]
 [437.84 438.  ]
 [456.98 463.28]]
